# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/agentstow/agentstow
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/agentstow/agentstow"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.5/agentstow-2.0.5-darwin-arm64.tar.gz"
      sha256 "527b9aa6cccd7fa022b90a6a271054acf6eca6a90667a6b0604138dedb3c0838"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.5/agentstow-2.0.5-darwin-x64.tar.gz"
      sha256 "061a96bb091cdf0bac9b78f38fbe0926ab3fcc0f84b8d710a2180d5c58f2142e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.5/agentstow-2.0.5-linux-arm64.tar.gz"
      sha256 "0817c89610dc2569cefef621146e85dde76b6e075b1df02e4abd0c27aa190528"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.5/agentstow-2.0.5-linux-x64.tar.gz"
      sha256 "1f4edbb403ad61d1f4813ea316871777a0c0323e6f7e9e74a33a6daef8e5a822"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
