# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/agentstow/agentstow
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/agentstow/agentstow"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.2/agentstow-2.0.2-darwin-arm64.tar.gz"
      sha256 "83903ecd11b6848e0b5df0bd3e8665868cc068e387f827fd39b8f2f852f91978"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.2/agentstow-2.0.2-darwin-x64.tar.gz"
      sha256 "6beaa7a29140cc010f8e2692ea3d7eac356b72b5295b6f41148f1ed0b2082a68"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.2/agentstow-2.0.2-linux-arm64.tar.gz"
      sha256 "120ab74875ae0fbf322ebfc5959572f64732c80dabb738327cf2e1d24d435b36"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v2.0.2/agentstow-2.0.2-linux-x64.tar.gz"
      sha256 "240d4bb33adb843f15768365268efc5aa00fde8addce4415dd88983f533279c5"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
