# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/agentstow/agentstow
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/agentstow/agentstow"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v1.0.0/agentstow-1.0.0-darwin-arm64.tar.gz"
      sha256 "0609c3b71ca142ed508844974d040c5535a11764df3048fbceb418161fe4a04b"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v1.0.0/agentstow-1.0.0-darwin-x64.tar.gz"
      sha256 "bdc21cf6609649221fe2e9089c5a5ce8c1a31f33f57659accb00b8622d627541"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/agentstow/agentstow/releases/download/v1.0.0/agentstow-1.0.0-linux-arm64.tar.gz"
      sha256 "97ca1cd53aa08a3c3e9ca2c9eda51ae6162498cb2e6e1366fe00d37939a88b96"
    end
    on_intel do
      url "https://github.com/agentstow/agentstow/releases/download/v1.0.0/agentstow-1.0.0-linux-x64.tar.gz"
      sha256 "0f63364f4fd4e780bfd025e093a4d5a604a45e0e7f340c590c9a97693cf7c561"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
