#!/usr/bin/env bash
# Rewrite Formula/agentstow.rb to point at the release assets of one tag.
#
#   scripts/update-formula.sh <tag>
#
# The checksums come from the SHA256SUMS.txt already published on that release,
# so the formula can only ever describe assets that exist. The whole file is
# regenerated rather than patched: there is no half-updated state where the
# version says one thing and a sha256 still says another.
#
# The `tap` job in .github/workflows/release.yml runs this on every v* tag and
# commits the result to main; running it by hand is the manual fallback.
set -euo pipefail

REPO="${AGENTSTOW_REPO:-agentstow/agentstow}"
TARGETS="darwin-arm64 darwin-x64 linux-arm64 linux-x64"

tag="${1:-}"
if [ -z "$tag" ]; then
  echo "usage: scripts/update-formula.sh <tag>   (e.g. v2.0.1)" >&2
  exit 2
fi
version="${tag#v}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh release download "$tag" --repo "$REPO" --pattern SHA256SUMS.txt --dir "$tmp" --clobber

# sha256sum writes "<hash>  <name>", and "<hash> *<name>" in binary mode; match
# either rather than assuming which one produced the file.
sum_for() {
  awk -v want="agentstow-$version-$1.tar.gz" \
    '$2 == want || $2 == "*" want { print $1 }' "$tmp/SHA256SUMS.txt" | head -1
}

for target in $TARGETS; do
  if ! [[ "$(sum_for "$target")" =~ ^[0-9a-f]{64}$ ]]; then
    echo "no sha256 for agentstow-$version-$target.tar.gz in the $tag SHA256SUMS.txt" >&2
    exit 1
  fi
done

asset() { echo "https://github.com/$REPO/releases/download/$tag/agentstow-$version-$1.tar.gz"; }

mkdir -p "$root/Formula"
cat > "$root/Formula/agentstow.rb" <<RUBY
# Generated by scripts/update-formula.sh on every release — do not edit by hand.
#
# The tap lives in the agentstow repository itself rather than a separate
# homebrew-agentstow one, so it is tapped by URL:
#
#   brew tap agentstow/tap https://github.com/$REPO
#   brew install agentstow
class Agentstow < Formula
  desc "One canonical .agents/ folder, fanned out to all your AI coding agents"
  homepage "https://github.com/$REPO"
  license "MIT"

  on_macos do
    on_arm do
      url "$(asset darwin-arm64)"
      sha256 "$(sum_for darwin-arm64)"
    end
    on_intel do
      url "$(asset darwin-x64)"
      sha256 "$(sum_for darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "$(asset linux-arm64)"
      sha256 "$(sum_for linux-arm64)"
    end
    on_intel do
      url "$(asset linux-x64)"
      sha256 "$(sum_for linux-x64)"
    end
  end

  def install
    bin.install "agentstow"
  end

  test do
    assert_match "agentstow #{version}", shell_output("#{bin}/agentstow --version")
  end
end
RUBY

echo "Formula/agentstow.rb now points at $tag"
