//! Rendered whole files — marker identity (ADR-0003).
//!
//! Some agents want a config in a shape a symlink cannot provide: Gemini takes
//! slash commands as TOML, while the Store keeps them as markdown. Those files
//! are generated wholesale, and every one carries a Marker on its first line.
//!
//! The Marker is what makes deletion safe. A file carrying it was written by
//! agentstow and can be overwritten or pruned; a file without one was written
//! by somebody else and is never touched — which is why this is the only family
//! that prunes without being asked by name.
//!
//! The Marker is a comment, so it is invisible to the agent reading the file.
//! That is the distinction from the MCP rule against markers: there a marker
//! would have had to live inside data the agent parses as configuration.

use std::path::PathBuf;

use crate::config::Config;
use crate::env::Env;
use crate::registry::{Commands, Format};
use crate::store::Store;
use crate::target;

/// The line that says a file is agentstow's to overwrite.
pub const MARKER: &str = "# agentstow: this file is generated — edit the Store instead";

/// What agentstow found at one rendered destination.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    /// Ours, and already exactly what the Store renders.
    Managed,
    /// The Store has this entry and the file is not there.
    Missing,
    /// Ours, but its contents have been changed.
    Drifted,
    /// Ours, and the Store entry it came from is gone.
    Orphaned,
    /// No Marker: somebody else wrote this. Never touched.
    Foreign,
}

impl State {
    pub fn needs_change(&self) -> bool {
        matches!(self, State::Missing | State::Drifted | State::Orphaned)
    }

    pub fn actionable(&self) -> bool {
        self.needs_change()
    }

    pub fn label(&self) -> &'static str {
        match self {
            State::Managed => "managed",
            State::Missing => "missing",
            State::Drifted => "drifted",
            State::Orphaned => "orphaned",
            State::Foreign => "foreign",
        }
    }

    pub fn note(&self) -> &'static str {
        match self {
            State::Managed => "",
            State::Missing => "not rendered yet",
            State::Drifted => "edited by hand — the Store version will be restored",
            State::Orphaned => "no longer in the Store — will be removed",
            State::Foreign => "not generated by agentstow — left alone",
        }
    }
}

/// One rendered destination.
#[derive(Debug, Clone)]
pub struct Item {
    pub target: String,
    pub name: String,
    pub path: PathBuf,
    pub state: State,
    body: Option<String>,
}

#[derive(Debug)]
pub struct Error {
    pub message: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.message)
    }
}

/// Survey every Target that takes rendered commands.
pub fn survey(env: &Env, config: &Config, store: &Store) -> Result<Vec<Item>, Error> {
    let scan = store.scan(crate::family::Family::Commands);
    let mut items = Vec::new();

    for target in target::resolve(env, config) {
        let Some(agent) = target.agent else {
            continue;
        };
        let Commands::Render { dir, format } = agent.commands else {
            continue;
        };
        let dir = env.in_home(dir);

        for entry in &scan.entries {
            let source = std::fs::read_to_string(&entry.path).map_err(|e| Error {
                message: format!("cannot read {}: {e}", entry.path.display()),
            })?;
            let body = render(&source, format)?;
            let path = dir.join(format!("{}.{}", entry.name, extension(format)));

            let state = match std::fs::read_to_string(&path) {
                Err(_) => State::Missing,
                Ok(current) if !is_ours(&current) => State::Foreign,
                Ok(current) if current == body => State::Managed,
                Ok(_) => State::Drifted,
            };

            items.push(Item {
                target: target.name.clone(),
                name: entry.name.clone(),
                path,
                state,
                body: Some(body),
            });
        }

        // Files we generated whose Store entry has gone. Safe to remove: the
        // Marker is proof we wrote them.
        let wanted: Vec<String> = scan.entries.iter().map(|e| e.name.clone()).collect();
        if let Ok(read) = std::fs::read_dir(&dir) {
            for found in read.flatten() {
                let path = found.path();
                let name = path
                    .file_stem()
                    .map(|s| s.to_string_lossy().into_owned())
                    .unwrap_or_default();
                if wanted.contains(&name) {
                    continue;
                }
                let ours = std::fs::read_to_string(&path)
                    .map(|text| is_ours(&text))
                    .unwrap_or(false);
                if !ours {
                    continue;
                }
                items.push(Item {
                    target: target.name.clone(),
                    name,
                    path,
                    state: State::Orphaned,
                    body: None,
                });
            }
        }
    }

    Ok(items)
}

/// Write or remove one rendered file.
pub fn apply(item: &Item) -> Result<(), Error> {
    match item.state {
        State::Missing | State::Drifted => {
            let body = item.body.as_ref().expect("a render to write");
            if let Some(parent) = item.path.parent() {
                std::fs::create_dir_all(parent).map_err(|e| Error {
                    message: format!("cannot create {}: {e}", parent.display()),
                })?;
            }
            crate::write::atomic(&item.path, body.as_bytes()).map_err(|e| Error {
                message: format!("cannot write {}: {e}", item.path.display()),
            })?;
            Ok(())
        }
        State::Orphaned => std::fs::remove_file(&item.path).map_err(|e| Error {
            message: format!("cannot remove {}: {e}", item.path.display()),
        }),
        _ => Ok(()),
    }
}

/// Whether this text was generated by agentstow.
fn is_ours(text: &str) -> bool {
    text.lines().take(3).any(|line| line.trim() == MARKER)
}

fn extension(format: Format) -> &'static str {
    match format {
        Format::Toml => "toml",
        Format::Json => "json",
    }
}

/// Turn a Store markdown command into one agent's native file.
fn render(source: &str, format: Format) -> Result<String, Error> {
    let (frontmatter, body) = split_frontmatter(source);
    let description = frontmatter
        .iter()
        .find(|(key, _)| key == "description")
        .map(|(_, value)| value.clone());

    match format {
        Format::Toml => {
            let mut doc = toml_edit::DocumentMut::new();
            if let Some(description) = description {
                doc["description"] = toml_edit::value(description);
            }
            doc["prompt"] = toml_edit::value(body.trim_end().to_string());
            Ok(format!("{MARKER}\n{doc}"))
        }
        Format::Json => {
            let mut object = serde_json::Map::new();
            if let Some(description) = description {
                object.insert("description".into(), serde_json::Value::from(description));
            }
            object.insert("prompt".into(), serde_json::Value::from(body.trim_end()));
            let text =
                serde_json::to_string_pretty(&serde_json::Value::Object(object)).map_err(|e| {
                    Error {
                        message: format!("cannot serialise a rendered command: {e}"),
                    }
                })?;
            Ok(format!("{text}\n"))
        }
    }
}

/// Split a markdown file's `---` frontmatter from its body.
///
/// Only the flat `key: value` lines are read; a command's frontmatter is not a
/// place agentstow needs to understand YAML in general.
fn split_frontmatter(source: &str) -> (Vec<(String, String)>, String) {
    let mut lines = source.lines();
    if lines.next().map(str::trim) != Some("---") {
        return (Vec::new(), source.to_string());
    }

    let mut fields = Vec::new();
    let mut rest = String::new();
    let mut in_body = false;

    for line in lines {
        if !in_body {
            if line.trim() == "---" {
                in_body = true;
                continue;
            }
            if let Some((key, value)) = line.split_once(':') {
                fields.push((
                    key.trim().to_string(),
                    value.trim().trim_matches(['"', '\'']).to_string(),
                ));
            }
            continue;
        }
        rest.push_str(line);
        rest.push('\n');
    }

    // No closing marker: treat the whole thing as body rather than guessing.
    if !in_body {
        return (Vec::new(), source.to_string());
    }
    (fields, rest.trim_start_matches('\n').to_string())
}
